### ISSUE TITLE
Training failure problem

### ISSUE THREAD

**Issue by WFLiu0327** [tiongleslie/3D-C2FT#2]
Hello, I am recently been working on 3D reconstruction. I tried to run your 3D-C2RT project. I just replaced the CNN encoder with ConvNeXt-Large which has better representation ability, as well as modified the size of batch-size, but my loss function does not drop when I train up. What do you think this may be due to? We will cite your article in our near future work, hope to get your reply.

**Comment by tianbao-li** [comment]
I have encountered the same problem as you. I reproduced the original code without any modifications, but after training for 300 epochs, the loss has not decreased.

**Comment by tianbao-li** [comment]
I tried the learning rate settings in the paper, but it didn't work.

**Comment by WFLiu0327** [comment]
Do you think it's possible that the code just doesn't work well?

**Comment by WFLiu0327** [comment]
Let's communicate directly in Chinese.

**Comment by tianbao-li** [comment]
I want to know if there is a problem with my reproduction code, or the training time is not long enough, I wonder if the author can provide the training loss curve

**Comment by george-kalitsios** [comment]
I'm facing the same issue; even after 400 epochs of training, the loss has not decreased. Did you come up with a solution?

**Comment by Chu-Orion** [comment]
在运行代码的时候遇到了下面的问题，请问各位大佬，这个该怎么解决啊，下面是具体的报错信息：

Traceback (most recent call last):
  File "eval.py", line 160, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "eval.py", line 155, in main
    eval_our(config.our_dataset_path, model)
  File "eval.py", line 88, in eval_our
    imgs = eval_transforms(imgs)
  File "/root/3D-C2FT/data/data_transforms.py", line 30, in __call__
    rendering_images = t(rendering_images)
  File "/root/3D-C2FT/data/data_transforms.py", line 57, in __call__
    rendering_images -= self.mean
ValueError: operands could not be broadcast together with shapes (0,) (3,) (0,) 

求帮助，谢谢了

**Comment by Chu-Orion** [comment]
I encountered the following problem when running the code, please ask you guys, how to tackle this? the following is the specific error message:

Traceback (most recent call last):
File "eval.py", line 160, in
main(parse_arguments(sys.argv[1:]))
File "eval.py", line 155, in main
eval_our(config.our_dataset_path, model)
File "eval.py", line 88, in eval_our
imgs = eval_transforms(imgs)
File "/root/3D-C2FT/data/data_transforms.py", line 30, in call
rendering_images = t(rendering_images)
File "/root/3D-C2FT/data/data_transforms.py", line 57, in call
rendering_images -= self.mean
ValueError: operands could not be broadcast together with shapes (0,) (3,) (0,)

thank you !!!!!

**Comment by he0713** [comment]
> 我想知道是不是我的复现代码有问题，或者训练时间不够长，不知道作者能不能提供训练损失曲线

训练代码不需要修改吗，我这里训练代码根本跑不动
